name: nginx release

on:
  pull_request:
      branches:
        - main
jobs:
  deploy:
    name: nginx release
    runs-on: ubicloud-standard-8-ubuntu-2404
    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: 🏗 Setup repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Set up Docker Context for Buildx
        run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: Docker meta
        id: nginx
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pigri/arxignis/nginx
          tags: |
            type=sha,format=short
            type=match,pattern=v(\d+\.\d+\.\d+),group=1
            type=match,pattern=v(\d+\.\d+),group=1
            type=match,pattern=v(\d+),group=1
            type=raw,value=latest

      - name: Build
        uses: docker/build-push-action@v6
        id: build-image
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: false
          tags: ${{ steps.nginx.outputs.tags }}
          labels: ${{ steps.nginx.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
